#!/bin/bash

TEMPORARY_HOSTS_BANNER="# this is a tmp file generated by inlunch, will be deleted"

if [ ! -v DIR -o -z "$DIR" ]; then
    echo "DIR env variable not set or zero length"
    exit 1
fi

function get_answer_file_path() {
    echo "${INLUNCH_ANSWERS:-answers.yml}"
}

# creates a temporary hosts file if necessary
# first argument is hosts file template to use with INLUNCH_FQDN
function get_hosts_file_path() {
    if [ "$#" -ne 1 -o -z "$1" ]; then
        echo "get_hosts_file_path misformatted parameters"
        exit 1
    fi

    if [ -v INLUNCH_FQDN ]; then
        mkdir "$DIR/tmp" &> /dev/null || true
        GENERATED_HOSTS_FILE="$DIR/tmp/hosts.$INLUNCH_FQDN"
        cp "$1" "$GENERATED_HOSTS_FILE"
        echo -e "\n$TEMPORARY_HOSTS_BANNER" >> "$GENERATED_HOSTS_FILE"
        sed -i -e "s/my_instack_machine.example.org/$INLUNCH_FQDN/g" "$GENERATED_HOSTS_FILE"
        echo "$GENERATED_HOSTS_FILE"
    else
        echo "${INLUNCH_HOSTS:-hosts.instack-virt}"
    fi
}

# removes hosts file if it contains $TEMPORARY_HOSTS_BANNER
# first argument is the hosts file to check and optionally remove
function remove_hosts_file_if_temporary() {
    if [ -z "$1" ]; then
        echo "get_hosts_file_path first argument has zero length"
        exit 1
    fi

    if grep "$TEMPORARY_HOSTS_BANNER" "$1" &> /dev/null; then
        rm "$1"
    fi
}
